import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../..');

function loadEnv() {
  const envLocalPath = path.join(rootDir, '.env.local');
  if (fs.existsSync(envLocalPath)) {
    try {
      process.loadEnvFile(envLocalPath);
    } catch {}
  }
  const envPath = path.join(rootDir, '.env');
  if (fs.existsSync(envPath)) {
    try {
      process.loadEnvFile(envPath);
    } catch {}
  }
}

loadEnv();

const VOICE_ID = process.env.ELEVENLABS_VOICE_ID?.trim() || 'bIHbv24MWmeRgasZH58o';
const VOICE_NAME = 'Will – Relaxed Optimist';
const ELEVENLABS_MODEL = process.env.ELEVENLABS_MODEL || 'eleven_turbo_v2_5';

export async function generatePresentationVoice() {
  console.log('Provider: ElevenLabs');
  console.log(`Voice: ${VOICE_NAME}`);
  console.log(`Voice ID: ${VOICE_ID}\n`);

  const jsonPath = path.join(rootDir, 'generated/presentation/presentation.json');
  if (!fs.existsSync(jsonPath)) {
    console.error(`[ERROR] Presentation script not found at ${jsonPath}. Run presentation:script first.`);
    process.exit(1);
  }

  const presentationData = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
  const audioOutputDir = path.join(rootDir, 'public/media/audio');
  fs.mkdirSync(audioOutputDir, { recursive: true });

  const audioFilePath = path.join(audioOutputDir, 'fauzaan-presentation.mp3');
  const statusFilePath = path.join(audioOutputDir, 'fauzaan-presentation.json');

  const elevenApiKey = process.env.ELEVENLABS_API_KEY?.trim();

  if (!elevenApiKey) {
    const errorMsg = 'ELEVENLABS_API_KEY is not configured in .env.local. Generation stopped.';
    console.error(`[ELEVENLABS ERROR] ${errorMsg}`);
    writeGenerationStatus(statusFilePath, {
      provider: 'ElevenLabs',
      voiceName: VOICE_NAME,
      voiceId: VOICE_ID,
      status: 'error',
      errorCode: 'MISSING_API_KEY',
      errorMessage: errorMsg,
      timestamp: new Date().toISOString(),
      segments: presentationData.segments,
    });
    // Ensure invalid audio is not present
    if (fs.existsSync(audioFilePath)) {
      fs.unlinkSync(audioFilePath);
    }
    process.exit(1);
  }

  console.log(`[ELEVENLABS] Calling ElevenLabs text-to-speech API for Voice ID: ${VOICE_ID}...`);
  const fullText = presentationData.segments.map((s) => s.script).join('\n\n');

  try {
    const streamEndpoint = `https://api.elevenlabs.io/v1/text-to-speech/${VOICE_ID}`;
    const streamRes = await fetch(streamEndpoint, {
      method: 'POST',
      headers: {
        'xi-api-key': elevenApiKey,
        'Content-Type': 'application/json',
        Accept: 'audio/mpeg',
      },
      body: JSON.stringify({
        text: fullText,
        model_id: ELEVENLABS_MODEL,
        voice_settings: {
          stability: 0.45,
          similarity_boost: 0.85,
          style: 0.25,
          use_speaker_boost: true,
        },
      }),
    });

    if (streamRes.ok) {
      const audioBuffer = Buffer.from(await streamRes.arrayBuffer());
      fs.writeFileSync(audioFilePath, audioBuffer);
      console.log(`\n[SUCCESS] Audio successfully generated by ElevenLabs using Voice ID ${VOICE_ID}!`);
      console.log(`[AUDIO INFO] Saved to: ${audioFilePath} (${(audioBuffer.length / 1024 / 1024).toFixed(2)} MB)`);

      writeGenerationStatus(statusFilePath, {
        provider: 'ElevenLabs',
        voiceName: VOICE_NAME,
        voiceId: VOICE_ID,
        status: 'success',
        audioFile: '/media/audio/fauzaan-presentation.mp3',
        fileSizeBytes: audioBuffer.length,
        timestamp: new Date().toISOString(),
        totalDuration: presentationData.totalEstimatedDuration,
        segments: presentationData.segments,
      });

      return true;
    } else {
      const errText = await streamRes.text();
      let parsedError = errText;
      try {
        const jsonErr = JSON.parse(errText);
        parsedError = jsonErr.detail?.message || jsonErr.message || JSON.stringify(jsonErr.detail || jsonErr);
      } catch {}

      console.error('\n====================================================');
      console.error('  [GENERATION STOPPED] ElevenLabs API Call Failed');
      console.error('  Provider: ElevenLabs');
      console.error(`  Voice: ${VOICE_NAME}`);
      console.error(`  Voice ID: ${VOICE_ID}`);
      console.error(`  HTTP Status: ${streamRes.status}`);
      console.error(`  Error: ${parsedError}`);
      console.error('====================================================\n');
      console.error('[STRICT POLICY] Fallback voices are disabled. No audio was substituted.');

      // Remove any existing audio file so an unverified voice is never played
      if (fs.existsSync(audioFilePath)) {
        fs.unlinkSync(audioFilePath);
        console.log('[CLEANUP] Deleted unverified fauzaan-presentation.mp3');
      }

      writeGenerationStatus(statusFilePath, {
        provider: 'ElevenLabs',
        voiceName: VOICE_NAME,
        voiceId: VOICE_ID,
        status: 'error',
        httpStatus: streamRes.status,
        errorMessage: parsedError,
        rawResponse: errText,
        timestamp: new Date().toISOString(),
        segments: presentationData.segments,
      });

      process.exit(1);
    }
  } catch (err) {
    console.error('\n====================================================');
    console.error('  [GENERATION STOPPED] Network / Connection Error');
    console.error('  Provider: ElevenLabs');
    console.error(`  Voice: ${VOICE_NAME}`);
    console.error(`  Voice ID: ${VOICE_ID}`);
    console.error(`  Error: ${err.message}`);
    console.error('====================================================\n');
    console.error('[STRICT POLICY] Fallback voices are disabled. No audio was substituted.');

    if (fs.existsSync(audioFilePath)) {
      fs.unlinkSync(audioFilePath);
    }

    writeGenerationStatus(statusFilePath, {
      provider: 'ElevenLabs',
      voiceName: VOICE_NAME,
      voiceId: VOICE_ID,
      status: 'error',
      errorMessage: err.message,
      timestamp: new Date().toISOString(),
      segments: presentationData.segments,
    });

    process.exit(1);
  }
}

function writeGenerationStatus(filePath, statusObj) {
  fs.writeFileSync(filePath, JSON.stringify(statusObj, null, 2), 'utf8');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  generatePresentationVoice().catch((err) => {
    console.error('[FATAL] generatePresentationVoice threw unhandled error:', err);
    process.exit(1);
  });
}
